// <auto-generated />
using System;
using LernFuchs.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LernFuchs.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701154016_RemoveMeaningTurkish_AddDifficultWords")]
    partial class RemoveMeaningTurkish_AddDifficultWords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("LernFuchs.Api.Models.ComprehensionQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Options")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadingPassageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReadingPassageId");

                    b.ToTable("ComprehensionQuestions");
                });

            modelBuilder.Entity("LernFuchs.Api.Models.ReadingPassage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("WordCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ReadingPassages");
                });

            modelBuilder.Entity("LernFuchs.Api.Models.VocabularyProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Box")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimesCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesWrong")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyWordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyWordId")
                        .IsUnique();

                    b.ToTable("VocabularyProgress");
                });

            modelBuilder.Entity("LernFuchs.Api.Models.VocabularyWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Antonyms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionGerman")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExampleSentence")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Plural")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Synonyms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WordType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Word");

                    b.ToTable("VocabularyWords");
                });

            modelBuilder.Entity("LernFuchs.Api.Models.ComprehensionQuestion", b =>
                {
                    b.HasOne("LernFuchs.Api.Models.ReadingPassage", "ReadingPassage")
                        .WithMany("Questions")
                        .HasForeignKey("ReadingPassageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingPassage");
                });

            modelBuilder.Entity("LernFuchs.Api.Models.VocabularyProgress", b =>
                {
                    b.HasOne("LernFuchs.Api.Models.VocabularyWord", "VocabularyWord")
                        .WithOne("Progress")
                        .HasForeignKey("LernFuchs.Api.Models.VocabularyProgress", "VocabularyWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyWord");
                });

            modelBuilder.Entity("LernFuchs.Api.Models.ReadingPassage", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("LernFuchs.Api.Models.VocabularyWord", b =>
                {
                    b.Navigation("Progress");
                });
#pragma warning restore 612, 618
        }
    }
}
